services:
  - type: web
    name: tornado-streamlit-app
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: streamlit run src/1_tornado_presentation.py
    plan: free